### ISSUE TITLE
Display Plume metadata when hovering over data

### ISSUE THREAD

**Issue by jerikac** [NASA-IMPACT/veda-config-ghg#35] opened 2023-08-11 21:23 UTC
Mid-priority ask from EMIT team. _Specific to EMIT Plume dataset_. The ask is to have metadata about the EMIT Plume datasets displayed when a user hovers over a particular instance of data. Specifically, the team has asked to display: 
- plume max, 
- uncertainty, 
- scene id, 
- time of observation (in UTC), 
- plume source, and 
- *emission rate. 
A similar feature is currently available in the EMIT team's VISION portal (see screenshot). *Emission rate metadata is not yet available and will be provided closer to R2. 
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/98853455/6b39f76b-bcb5-404a-a387-18a7f6f86043)

**Comment by aboydnw** [comment] 2023-08-14 16:37
This seems like a duplicate of https://github.com/NASA-IMPACT/veda-ui/issues/588 so I will close as not planned and link the two tickets

**Comment by danielfdsilva** [comment] 2023-08-15 09:47
Closing as stated above

**Closed by danielfdsilva** 2023-08-15 09:47 UTC
